[package]
name = "term"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
rustix-openpty = "0.1.1"
async-std = "1.13.0"
iced = "0.13.1"
once_cell = "1.20.2"
rusttype = "0.9.3"
font-loader = "0.11.0"

# ansi-parser
heapless = "0.8.0"
nom = "7.1.3"
